### ISSUE TITLE
Successful install -> initial blinking cursor when attempting to boot Deb 12 -> bootloader now skips Deb 12 & loads Windows instead

### ISSUE THREAD

**Issue by cameronj86** [r0b0/debian-installer#14]
Thanks for all the help! I feel like I'm so close but having trouble crossing the finish line. I have a Windows computer with an SDD running windows and a blank HDD that I'm installing 12 onto:

**Steps taken**

1. Download iso
2. Use Balena etcher to flash to usb stick
3. Confirm UEFI is the only boot option/fastboot is turned off
4. Reprioritize USB stick as number 1 boot method & blank HDD as number 2, and Windows SSD as number 3.
5. Boot via USB stick
6. During installation process, choose blank HDD
7. Wait for installation to complete
8. Shutdown PC and remove USB stick
9. Here, _one time_, the system attempted to load Deb 12 and I was met w/ a blinking cursor. Most times, my computer beeps, indicating an inability to load HDD as the number 1 boot method, so it cycles down to Windows instead. This has happened ~5 times in a row or so. 
10. I know the install was generally successful, because if I view disk formatting in Windows, I see three healthy partitions (Boot, EFI & Swap) on the previously unallocated HDD.

Spent about 2 hours troubleshooting last night. Here are my (uneducated) theories after a lot of googling:
**For some reason, the installer is not triggering a GRUB install** - As I've never seen a Linux-specific bootloader, this seems like the most likely culprit and where I've spent the most time. I was following this tutorial  ([Using A Live CD/USB To Fix Your Current System](https://wiki.debian.org/GrubEFIReinstall)) but could never get past step number 4 for some reason. I had to mkdir most of the mounts which may have overlooked something perhaps?
**My Nvidia graphics card needs a Debian software update** - This makes sense re: the blinking cursor I saw once, AFAIK, the system would still boot or provide the option to roll-over to terminal mode. I actually started the process of downloading nvidia-driver on the 'live' installation, but felt like the install would only affect the installer on the flash disk instead of the HDD and aborted the install midway. It seemed like a waste of time customizing the installer version but perhaps I'm mistaken here?
**UEFI is still not being seen during the install** - During my initial install that failed, my boot settings were set to auto. (This _might_ have been the one instance w/ a blinking cursor now that I think about it) I have since changed my boot settings to UEFI-only and restarted the install, but no dice. I think this is the least likely culprit tbh, because I am able to see the EFI folder when I mounted the HDD to the 'live install' during my troubleshooting of potential issue number 1. 

Curious if there are any clear instances where I'm making a mistake or if you have any suggestions around mounting the HDD to the live-install to either install GRUB or pass along a graphics card update. Thanks!

**Comment by r0b0** [comment]
Hi Cameron,
First some answers to your questions and later my theories about what could be wrong and how to fix this.
1. The installer doesn't use grub but [systemd-boot](https://www.freedesktop.org/wiki/Software/systemd/systemd-boot/) as a boot loader
2. The proprietary nvidia drivers are not installed by the installer but this will probably not be an issue - the open source nouveau driver is included and, given that it works when the live system is running from the USB drive, it should work the same when the installed system is running.

Now to my theories:
1. The system is in fact booting up but it gets stuck somewhere and you don't see where and why because it is booting in "quiet" mode. Try turning the system off, boot it while pressing the space key and you should get into the systemd-boot menu. Then select the Debian item, press E to edit and remove words "quiet" and "splash" from the command. Press enter to continue booting. This is all described in details at https://www.freedesktop.org/wiki/Software/systemd/systemd-boot/ Now you will get a lot of information about the kernel and system boot. 
2. Another option is that the installer reported success but in fact failed to perform some of the steps. Can you go through the installation one more time and this time download the log file and read through it? Or attach it here. Maybe there is an error message there somewhere and I can fix the error handling.

Kind regards,
Robert

**Comment by r0b0** [comment]
Oh, and about UEFI/legacy - the installer assumes UEFI, will not work with legacy/MBR/BIOS mode, I think the live system from USB won't even boot without UEFI, so as you say, this is least likely to be the issue.

**Comment by cameronj86** [comment]
Just got back from a vacation this morning and have since spent a few hours today troubleshooting.

I did try using spacebar to intervene, and it did trigger a new splash screen, but the screen appears to be based on the system deducing that a key is stuck when I press (or hold) the spacebar. The only options were to resume the boot, or to go to settings which was the default BIOS screen. I also tried [Shift and/or Esc](https://askubuntu.com/questions/16042/how-to-get-to-the-grub-menu-at-boot-time) but no dice there either.

Prior to your response last week, I somehow managed to lock myself out of Windows too 😂. I set up [Grub2Win](https://sourceforge.net/projects/grub2win/) and I think one of the suggested options ("Force Unconditional Load Of Grub2Win") is the culprit from my newfound Windows-specific issues. It's entirely possible that the 'space bar', shift or esc would work, but the Grub2Win settings are blocking Windows and Debian from loading at this point. 

At this rate, this experience could be the 'burn the ships' moment where I fully commit to Debian, but I guess it's hard for me to commit to wiping the SSD if I can't even boot the HDD lol. I'm going to try to boot in safe mode and retry the full install again and see what happens

**Comment by cameronj86** [comment]
I  wiped Windows from my main SSD in an ill-advised troubleshooting hail mary, so I'm all in on Debian at this point lol.

Back to Linux specific-troubleshooting:

1. Here are my results from the installer. ([Pastebin](https://pastebin.com/zQXUDA9V)) 
2. I also flashed the BIOS with the latest version I could find online after [seeing this solution](https://askubuntu.com/questions/1414366/no-operating-system-found-after-clean-install-of-ubuntu-22-04), but that didn't result in an additional 'CSM' option like the answerer received. The computer still boots so no harm no foul at least.
3. Below is a photo that I think might be a window into the root issue. For context, I flashed an ISO of [boot-repair](https://sourceforge.net/projects/boot-repair/) onto a flash drive and used it to troubleshoot. The [photo](https://i.imgur.com/JUvPVhK.png) _shows that I can boot via UEFI or Legacy for the USB stick, but AFAIK, most importantly it shows that the SSD & HDD aren't showing a bootable OS._ As a result of this (& number 2) I don't think this issue is BIOS-related. My new theory is that it might be 
4. Here is detailed breakdown of my system construct, [via boot-repair](https://pastebin.ubuntu.com/p/pJrxSKkrDb/). I tried to repair via the tool but to no avail. I'm not quite as well-versed in reading the logs but I have been parsing it for things to google. I'm hesitant to use the software again for troubleshooting, because I'm guessing there might be conflict between GRUB & systemd-boot?

Anyways, thanks for your help so far @r0b0 I'm officially out of solutions to try now but let me know if you have any ideas. In the interim I'm going to read up on the systemd-boot link you shared in case there's something else I can tweak. I did also try a netinstall of Debian too that was also 'successful' until I tried to launch it, so I'm not so sure that the boot manager is the issue but it's the only other thing I can think of.

**Comment by r0b0** [comment]
Can you check bios again and look for entries such as "secure boot" or "quick boot" and disable them all?

If not even the official debian installer works on this machine then I am  out of ideas too.

There are no errors in the log file.

**Comment by cameronj86** [comment]
I did those already unfortunately. 

No worries though, I bought a used OptiPlex and was able to get Debian dual booted w/ Windows. Thanks for your assistance and putting the install guide together 🫡
