### ISSUE TITLE
Script is incompatible with an NVMe drive

### ISSUE THREAD

**Issue by meyvin** [r0b0/debian-installer#15]
When using an NVMe drive that is automatically mounted at the default location when using a single NVME drive: /dev/nvme0n1, your script does not function properly. It fails to create the partitions correctly. Consequently, when the script attempts to resize your root partition, it intends to overwrite the entire disk instead of the designated root partition.

Your script relies on specific hard coded partition numbers, whereas Linux represents partition numbers for NVMe drivers using "p1", "p2" etc. See: https://utcc.utoronto.ca/~cks/space/blog/linux/NVMeDeviceNames.

**Comment by r0b0** [comment]
Hi meyvin,

Thank you for the report. I have fixed the issue by addressing partitions by their UUIDs instead of assuming naming conventions in /dev/

I do not have any NVMe hardware so I only tested this with SATA. Can you test the version of the script from the fix_nvme branch and confirm, please?

Thanks.

**Comment by meyvin** [comment]
First of all, thanks for the quick update! I encountered a few minor issues, but apart from that, it's working perfectly:

1. I chose not to use a swap partition (I prefer zswap). The efi_partition variable is not defined in your if/else block on line 70 when setting ENABLE_SWAP as false. As a result, the script fails when attempting to create the EFI partition.
2. On line 397, swapoff is used. I don't think this is applicable if you don't choose a swap partition.
3. TPM2 doesn't seem to be working in my case. The script does indicate the following: "New TPM2 token enrolled as key slot 2" However, when I boot, I still have to enter my LUKS password.

**Comment by r0b0** [comment]
Thanks, 1+2 fixed. 

Re: 3 - you can play around with the [PCRs parameters](https://www.freedesktop.org/software/systemd/man/systemd-cryptenroll.html#--tpm2-pcrs=PCR) for enrolling the TPM.  

If you set the parameter to nothing e.g. --tpm2-pcrs=  it means that TPM will unlock no matter what. The script is currently using 7+14 as this is apparently the value recommended by people who know more than I do about TPM.
