### ISSUE TITLE
Cannot install when an empty SD card reader is present

### ISSUE THREAD

**Issue by stusmi** [r0b0/debian-installer#19]
get_block_devices() in App.vue errors on my system due to the presence of a SD card reader with no media inserted.
for(const child of device.children) fails as the empty SD reader has no record of children in the JSON. The result is that all devices are marked as not available.

**Comment by r0b0** [comment]
Hi, can you post output of `sudo lsblk -OJ` from this system, please? 

This is the source of the JSON in the back-end. I will fix the issue in the front-end code.
